name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          TRANSMUTE_CLIENT_ID: ${{ secrets.TRANSMUTE_CLIENT_ID }}
          TRANSMUTE_CLIENT_SECRET: ${{ secrets.TRANSMUTE_CLIENT_SECRET }}
        run: npm run test
